### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by mspoulsen** [vuetifyjs/eslint-plugin-vuetify#27] opened 2021-02-15 10:32 UTC
When running `npm install eslint-plugin-vuetify --save-dev` I get:

```
Found: eslint@7.19.0

Could not resolve dependency:
npm ERR! peer eslint@"^6.0.0 | ^7.0.0" from eslint-plugin-vuetify@1.0.0-beta.7
```
This does really make sense, does it? I have 7.19.0 installed which should be fine.

I am using npm 7.5.3.

Any ideas?

**Comment by KaelWD** [comment] 2021-02-16 14:25
Duplicate of #26

**Closed by KaelWD** 2021-02-16 14:25 UTC
