### ISSUE TITLE
False `no-deprecated-props` error  on VBtn

### ISSUE THREAD

**Issue by abea** [vuetifyjs/eslint-plugin-vuetify#62] opened 2023-05-25 16:35 UTC
VBtn throws an error for the `text` prop for `vuetify/no-deprecated-props`. That prop is listed in the docs and does have the intended effect. The linter will automatically try to change it to `variant="text"`, which is correct for v2 to v3, but doesn't support the new v3 version of the prop (and long-term use of the linter).

**Comment by KaelWD** [comment] 2023-05-25 16:35
Duplicate of #59

**Closed by KaelWD** 2023-05-25 16:35 UTC
