### ISSUE TITLE
how to add the plugin in eslint.config.js

### ISSUE THREAD

**Issue by sachinkmohan** [vuetifyjs/eslint-plugin-vuetify#94] opened 2024-04-10 13:17 UTC
I'm not using the old eslintrc.js instead eslint.config.js, which is the new standard recommended by eslint from version 9 onwards on their website https://eslint.org/docs/latest/use/configure/configuration-files. Not sure how to add this plugin to this list, just like I did for Vue 3. 

Any help would be useful!

```
import pluginVue from "eslint-plugin-vue";

export default [
  ...pluginVue.configs["flat/essential"],
  ...pluginVue.configs["flat/recommended"],
  ...pluginVue.configs["flat/strongly-recommended"],
```

**Comment by KaelWD** [comment] 2024-04-10 14:58
Duplicate of #93

**Closed by KaelWD** 2024-04-10 14:58 UTC
