### ISSUE TITLE
v-slider @start and @end events are supported in Vuetify 3.2.0

### ISSUE THREAD

**Issue by joepavitt** [vuetifyjs/eslint-plugin-vuetify#79] opened 2023-11-22 16:46 UTC
https://github.com/vuetifyjs/eslint-plugin-vuetify/blob/a3d57fc00b57afbb3bac85682f3f644fbf5d1e0a/src/rules/no-deprecated-events.js#L120-L121C16

The linter does not permit the user of `v-slider` events `@end` and `@start`, despite both of these events being supported:

- Release Notes: https://vuetifyjs.com/en/getting-started/release-notes/#features
- V Slider Docs: https://vuetifyjs.com/en/api/v-slider/#events-end (note the events were added in Vuetify `3.2.0`)

**Comment by KaelWD** [comment] 2023-12-08 00:05
Duplicate of #74

**Closed by KaelWD** 2023-12-08 00:05 UTC
